-- =============================================
-- DONNÉES INITIALES - RESSOURCES SAN DIEGO
-- =============================================

-- GOVERNMENTAL RESOURCES
INSERT INTO public.resources (category, name, url, description, meeting_focus) VALUES
('governmental', 'San Diego County Sheriff''s Department - Narcotics Task Force (NTF)', 'https://www.sdsheriff.gov/', 'NTF is a multi-agency enforcement unit disrupting drug trafficking organizations (DTOs). It includes partnerships with DEA, CBP, and international agencies, focusing on fentanyl seizures, criminal networks, and cross-border surveillance.', 'Understand how law enforcement agencies collaborate to detect, intercept, and dismantle synthetic opioid trafficking operations.'),
('governmental', 'U.S. Customs and Border Protection (CBP) - San Diego Field Office', 'https://www.cbp.gov/contact/ports/san-diego', 'CBP manages interdiction at key San Diego border crossings, where most fentanyl enters the U.S. The San Diego Field Office uses detection technologies and coordinates with foreign enforcement partners.', 'Learn how CBP identifies and intercepts synthetic drugs at ports of entry and how international collaboration helps block fentanyl supply chains.'),
('governmental', 'Homeland Security Investigations (HSI) - San Diego', 'https://www.ice.gov/node/65589', 'HSI leads transnational investigations targeting fentanyl production and trafficking, cyber marketplaces, and chemical precursors. San Diego is a critical hub in HSI''s international cooperation programs.', 'Examine HSI''s strategies for dismantling synthetic drug networks and partnering with foreign agencies.'),
('governmental', 'San Diego County - Health & Human Services Agency (HHSA), Behavioral Health Services', 'https://www.sandiegocounty.gov/content/sdc/hhsa/programs/bhs.html', 'HHSA leads the region''s opioid response, tracking overdose data, distributing naloxone, and coordinating prevention and treatment services. They also lead the San Diego Opioid Task Force.', 'Explore how regional public health agencies track and respond to synthetic drug overdoses using integrated prevention and treatment approaches.');

-- ACADEMIC RESOURCES
INSERT INTO public.resources (category, name, url, description, meeting_focus) VALUES
('academic', 'SDSU Institute for Public Health - Center for Alcohol & Drug Studies and Services (CADSS)', 'https://socialwork.sdsu.edu/research/center-for-aod', 'Located within SDSU''s School of Public Health, CADSS conducts research, evaluation, and training in substance use prevention, treatment, and harm reduction. It partners with county departments and community-based organizations to address the opioid crisis.', 'Explore how research centers support local fentanyl mitigation efforts through data-driven prevention, evaluation of harm reduction programs, and partnerships with government and nonprofit agencies.');

-- NONPROFIT RESOURCES
INSERT INTO public.resources (category, name, url, description, meeting_focus) VALUES
('nonprofit', 'McAlister Institute - Addiction Recovery & Community Outreach', 'https://www.mcalisterinc.org/', 'McAlister Institute runs outpatient, residential, and detox programs focused on opioid recovery. It supports justice-involved individuals and works closely with the courts, offering alternative sentencing and relapse prevention.', 'Understand how nonprofits bridge the gap between justice systems and public health to provide addiction recovery solutions for fentanyl-impacted populations.'),
('nonprofit', 'SAY San Diego - Youth & Prevention Programs', 'https://www.saysandiego.org', 'SAY San Diego provides school and community prevention services focused on substance use. Their programming includes peer mentoring, parental education, and policy advocacy for youth protection.', 'Learn how early prevention programs engage schools, families, and communities to reduce youth exposure to synthetic opioids.');

-- CULTURAL ACTIVITIES
INSERT INTO public.resources (category, name, url, description, price, accessibility) VALUES
('cultural', 'San Diego Zoo', 'https://www.sandiegozoo.org/', 'The 100-acre Zoo is home to over 3,700 rare and endangered animals representing more than 650 species and subspecies, and a prominent botanical collection with more than 700,000 exotic plants.', '$62 for one Adult Ticket', 'The zoo is located just north of downtown San Diego in Balboa Park (a 5-10-minute drive from downtown).'),
('cultural', 'Harbor Cruise', 'https://www.sdhe.com/', 'Narrated tours covering ships of the Maritime Museum, Harbor and Shelter Islands, North Island Naval Air Station, the Submarine Base, the Coronado Bridge, and more.', '$30 for one-hour tour; $35 for full bay two-hour tour', 'The tour begins and ends at the same location downtown along Broadway Pier.'),
('cultural', 'USS Midway Museum', 'https://www.midway.org/', 'Experience life at sea aboard one of America''s longest-serving aircraft carriers. Explore more than 60 exhibits with a collection of 30 restored aircraft. Self-guided audio tour narrated by Midway sailors.', '$26 for one Adult General Admission Ticket', 'The museum is located downtown alongside Navy Pier. Operating Hours: 10am - 5pm.'),
('cultural', 'Balboa Park', 'https://www.balboapark.org/', 'Home to 17 major museums and cultural institutions, renowned performing arts venues, beautiful gardens and the San Diego Zoo. Ever-changing calendar of museum exhibitions, plays, musicals, concerts, and classes.', 'Free (individual attractions may have fees)', 'Conveniently located just north of downtown San Diego (a 5-10-minute drive from downtown).'),
('cultural', 'Old Town Trolley Tour', 'https://www.trolleytours.com/san-diego', 'Hop-on hop-off sightseeing tours highlighting the best San Diego attractions. 25-mile loop visiting 10 neighborhoods with 10 destination stops including the San Diego-Coronado Bridge.', '$44 for a 1-Day Adult Ticket', 'Hours of operation: 8:50am - 5:00pm. Multiple stops throughout San Diego.'),
('cultural', 'Coronado', 'https://coronadovisitorcenter.com/', 'Charming oceanfront community with beaches consistently voted among America''s finest. Features fine homes, mansions, and the historic Hotel del Coronado.', 'Free', 'Accessible via Coronado Bridge, Coronado Ferry, or water taxi. 15-20 minute drive from downtown.'),
('cultural', 'SeaWorld San Diego', 'https://www.seaworldparks.com/en/seaworld-sandiego', 'Experience the Orca Encounter, Dolphin Days, and Sea Lions Live shows. Thrilling rides like Electric Eel, Manta, and Journey To Atlantis. Feed dolphins and get up-close to beluga whales, polar bears, sharks and penguins.', '$99.99 for one Adult Ticket', '15-20 minute drive from downtown San Diego.');
